#!/usr/bin/env python3
"""Generate one LaTeX-ready figure per revision result.

This is deliberately separate from ``consolidate.py``: consolidation creates
tables and an audit trail; this script creates the individual panels needed in
the manuscript.  It reads existing result artefacts only and writes below
``revision_consolidated_tables_figures/individual_figures``.

Run from the repository root:
    python analysis/revision_consolidated_tables_figures/generate_individual_figures.py
"""
from __future__ import annotations

import ast
import re
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "results" / "revision_consolidated_tables_figures" / "individual_figures"
MASTER = ROOT / "results" / "revision_consolidated_tables_figures" / "data" / "master_results_summary.csv"
ABLATION = ROOT / "results" / "component_analysis_ablation" / "tables" / "contrasts_official.csv"
DRIFT = ROOT / "results" / "drift_diagnostics_10seeds" / "1.1_diagnostico_drift" / "drift_telemetry.csv"
PRIOR = ROOT / "results" / "global_prior_analysis" / "data" / "femnist_writer_metrics.csv"

# Copied verbatim from figuras_artigo.py.  Dimensions below use its ordinary
# single-plot canvas (6.5 x 4.6 in), rather than the concatenated wide panels.
COLORS = {"FedHAD": "#D62728", "FedAVG": "#1F77B4", "FedProx": "#2CA02C",
          "FedAvgM": "#9467BD", "FedNova": "#FF7F0E"}
MARKERS = {"FedHAD": "s", "FedAVG": "o", "FedProx": "D", "FedAvgM": "^",
           "FedNova": "P"}
DISPLAY = {"FedAVG": "FedAvg"}
ORDER = ["FedAVG", "FedAvgM", "FedProx", "FedNova", "FedHAD"]
LABELS = {"CIFAR10": "CIFAR-10", "FashionMNIST": "FashionMNIST",
          "MNIST": "MNIST", "FEMNIST": "FEMNIST"}

plt.rcParams.update({
    "figure.dpi": 150, "savefig.dpi": 300, "font.size": 13,
    "axes.labelsize": 13, "xtick.labelsize": 12, "ytick.labelsize": 12,
    "legend.fontsize": 11.5, "figure.facecolor": "white", "axes.facecolor": "white",
    "axes.grid": True, "grid.linestyle": "--", "grid.alpha": 0.35,
    "axes.axisbelow": True, "font.family": "sans-serif",
})


def name(method: str) -> str:
    return DISPLAY.get(method, method)


def handles(methods: list[str]) -> list[Line2D]:
    return [Line2D([0], [0], color=COLORS[m], marker=MARKERS[m], lw=2.0,
                   markersize=7, label=name(m)) for m in methods]


def save(fig, section: str, stem: str, caption: str, label: str) -> None:
    folder = OUT / section
    folder.mkdir(parents=True, exist_ok=True)
    base = folder / stem
    fig.savefig(Path(str(base) + ".png"), dpi=300, bbox_inches="tight")
    fig.savefig(Path(str(base) + ".pdf"), bbox_inches="tight")
    plt.close(fig)
    tex = f"""% Generated by generate_individual_figures.py -- do not edit by hand.
\\begin{{figure}}[t]
  \\centering
  \\includegraphics[width=\\columnwidth]{{revision_consolidated_tables_figures/individual_figures/{section}/{stem}.pdf}}
  \\caption{{{caption}}}
  \\label{{{label}}}
\\end{{figure}}
"""
    Path(str(base) + ".tex").write_text(tex, encoding="utf-8")


def pareto(points: list[tuple[float, float]]) -> set[int]:
    return {i for i, (cost, acc) in enumerate(points) if not any(
        (other_cost <= cost and other_acc >= acc) and
        (other_cost < cost or other_acc > acc)
        for j, (other_cost, other_acc) in enumerate(points) if i != j)}


def plot_pareto(master: pd.DataFrame) -> None:
    specs = [("MNIST", "test1_convergencia", 0.5),
             ("FashionMNIST", "test1_convergencia", 0.5),
             ("CIFAR10", "test1_convergencia", 0.5),
             ("FEMNIST", "test8_femnist", None)]
    for ds, tag, alpha in specs:
        q = master[(master.experiment_tag == tag) & (master.dataset == ds) & master.arm.isna()]
        if alpha is not None:
            q = q[np.isclose(q.alpha, alpha)]
        rows = []
        for method in ORDER:
            g = q[q.method == method]
            if not g.empty:
                rows.append((method, g.final_accuracy.mean(), g.final_accuracy.std(ddof=1),
                             g.tflops.mean(), g.tflops.std(ddof=1)))
        points = [(r[3], r[1]) for r in rows]
        front = pareto(points)
        span = max(x for x, _ in points) - min(x for x, _ in points)
        span = span or max(x for x, _ in points)
        colocated: dict[float, list[int]] = {}
        for i, (x, _) in enumerate(points):
            colocated.setdefault(round(x, 3), []).append(i)
        offsets = {}
        for group in colocated.values():
            for j, i in enumerate(group):
                offsets[i] = (j - (len(group) - 1) / 2) * 0.05 * span
        # Same canvas as figs/efficiency/scatter_accuracy_vs_tflops_alpha*.pdf.
        fig, ax = plt.subplots(figsize=(6.0, 4.6))
        for i, (method, acc, acc_sd, cost, cost_sd) in enumerate(rows):
            on_front = i in front
            ax.errorbar(cost + offsets[i], 100 * acc, xerr=cost_sd, yerr=100 * acc_sd,
                        fmt=MARKERS[method], color=COLORS[method], capsize=3,
                        markersize=11 if on_front else 8,
                        markeredgecolor="black" if on_front else "white",
                        markeredgewidth=1.4 if on_front else 0.8)
        pf = sorted(points[i] for i in front)
        if len(pf) > 1:
            ax.plot([x for x, _ in pf], [100 * y for _, y in pf], "--", color="0.35", lw=1.4)
        ax.set_xlabel("TFLOPs")
        ax.set_ylabel("Final accuracy (%)")
        ax.legend(handles=handles([r[0] for r in rows]), frameon=False, loc="best")
        save(fig, "01_efficiency", f"pareto_accuracy_compute_{ds}",
             f"Final accuracy versus realised training FLOPs on {LABELS[ds]}. Black-edged markers are non-dominated; error bars are one standard deviation over 30 seeds. Co-located fixed-budget baselines are offset horizontally only for legibility.",
             f"fig:pareto-{ds.lower()}")


def plot_target(master: pd.DataFrame) -> None:
    q = master[(master.experiment_tag == "test1_convergencia") & (master.dataset == "CIFAR10") &
               np.isclose(master.alpha, 0.5) & master.arm.isna()]
    methods, means, sds, fractions = [], [], [], []
    for method in ORDER:
        g = q[q.method == method]
        if g.empty:
            continue
        reached = g[g.target_70_reached == True]
        methods.append(method); means.append(reached.tflops_to_target_70.mean())
        sds.append(reached.tflops_to_target_70.std(ddof=1) if len(reached) > 1 else 0)
        fractions.append((len(reached), len(g)))
    fig, ax = plt.subplots(figsize=(6.5, 4.6))
    for i, method in enumerate(methods):
        partial = fractions[i][0] < fractions[i][1]
        ax.bar(i, means[i], yerr=sds[i], color=COLORS[method], width=.66, capsize=4,
               edgecolor="black", linewidth=.8, hatch="//" if partial else None)
        ax.text(i, means[i] + sds[i] + 12, f"{means[i]:.1f}", ha="center")
        if partial: ax.text(i, means[i] / 2, f"reached\\n{fractions[i][0]}/{fractions[i][1]}", ha="center", va="center", fontsize=10)
    ax.set_xticks(range(len(methods)), [name(m) for m in methods], rotation=12)
    ax.set_ylabel("TFLOPs to reach 70% accuracy")
    ax.text(.5, -.22, "Hatched: target not reached by all 30 seeds", transform=ax.transAxes, ha="center", fontsize=11)
    save(fig, "01_efficiency", "flops_to_target_70_CIFAR10",
         "FLOPs required to first reach 70% accuracy on CIFAR-10 at $\\alpha=0.5$; lower is better. Means use only seeds that reach the target, while the annotation reports the reach rate.",
         "fig:cost-to-target")


def plot_heterogeneity(master: pd.DataFrame) -> None:
    q = master[master.experiment_tag.isin(["test1_convergencia", "test2_robustez_alpha"]) & master.arm.isna()]
    for ds in ["MNIST", "FashionMNIST", "CIFAR10"]:
        # Same canvas as the single-dataset test2 figures in figs/.
        fig, ax = plt.subplots(figsize=(6.5, 4.4))
        present = []
        for method in ORDER:
            g = q[(q.dataset == ds) & (q.method == method)].groupby("alpha").final_accuracy
            if g.size().empty:
                continue
            stats = g.agg(["mean", "std"]).reset_index().sort_values("alpha")
            ax.errorbar(stats.alpha, 100 * stats["mean"], yerr=100 * stats["std"].fillna(0),
                        color=COLORS[method], marker=MARKERS[method], lw=2.0, markersize=7, capsize=3)
            present.append(method)
        ax.set_xscale("log"); ax.set_xticks([.01, .1, 1], ["0.01", "0.1", "1"])
        ax.set_xlabel(r"Dirichlet $\alpha$"); ax.set_ylabel("Final accuracy (%)")
        ax.legend(handles=handles(present), frameon=False, loc="best")
        save(fig, "02_heterogeneity", f"accuracy_vs_alpha_{ds}",
             f"Final accuracy as label skew varies on {LABELS[ds]}. Lower Dirichlet $\\alpha$ means stronger heterogeneity; error bars are one standard deviation over 30 seeds.",
             f"fig:alpha-{ds.lower()}")


def history(path: Path):
    text = path.read_text(encoding="utf-8", errors="replace")
    match = re.search(r"--- History \(metrics, centralized\) ---\s*(\{.*?\})", text, re.S)
    if not match:
        return None
    data = ast.literal_eval(match.group(1))
    acc = data.get("accuracy") or []
    return [(r, a) for r, a in acc if a is not None]


def plot_long_horizon(master: pd.DataFrame) -> None:
    q = master[(master.experiment_tag == "test7_plato") & (master.dataset == "CIFAR10") & master.arm.isna()]
    for alpha in [.5, .01]:
        # Same canvas as figs/test7/accuracy_convergence_50rounds.pdf.
        fig, ax = plt.subplots(figsize=(6.0, 4.2))
        present = []
        for method in ORDER:
            g = q[np.isclose(q.alpha, alpha) & (q.method == method)]
            series: dict[int, list[float]] = {}
            for rel in g.rel_path:
                parsed = history(ROOT / rel)
                if parsed:
                    for rnd, acc in parsed: series.setdefault(rnd, []).append(acc)
            if not series: continue
            rounds = np.array(sorted(series)); mean = np.array([np.mean(series[r]) for r in rounds])
            sd = np.array([np.std(series[r], ddof=1) if len(series[r]) > 1 else 0 for r in rounds])
            ax.plot(rounds, mean, color=COLORS[method], marker=MARKERS[method], lw=2.0, markersize=5, markevery=6)
            ax.fill_between(rounds, mean - sd, mean + sd, color=COLORS[method], alpha=.13, lw=0)
            present.append(method)
        ax.axvline(10, color=".35", ls=":", lw=1.5, label="10-round horizon")
        ax.set_xlabel("Communication round"); ax.set_ylabel("Centralized accuracy"); ax.set_ylim(0, 1)
        ax.legend(handles=handles(present) + [Line2D([0],[0], color=".35", ls=":", label="10-round horizon")], frameon=False, loc="lower right")
        a = str(alpha).replace(".", "_")
        save(fig, "03_long_horizon", f"accuracy_convergence_CIFAR10_alpha{a}",
             f"Fifty-round convergence on CIFAR-10 at $\\alpha={alpha:g}$. The vertical line marks the ten-round horizon used in the main grid; shaded bands show one standard deviation over 30 seeds.",
             f"fig:long-horizon-{a}")


def plot_ablation() -> None:
    d = pd.read_csv(ABLATION); d = d[d.analysis == "primary_all_seeds"]
    for alpha in [.01, .1]:
        q = d[np.isclose(d.alpha, alpha)].reset_index(drop=True)
        fig, ax = plt.subplots(figsize=(6.5, 4.6))
        labels = []
        for i, row in q.iterrows():
            color = "#333333" if row.equal_compute_contrast else "#8C564B"
            ax.errorbar(row.mean_diff_pp, i, xerr=[[row.mean_diff_pp-row.ci95_low_pp], [row.ci95_high_pp-row.mean_diff_pp]],
                        fmt="o", color=color, capsize=4, markersize=8, elinewidth=2)
            labels.append(row.question.split("?", 1)[0].replace(" does ", ": ").replace("?", ""))
        ax.axvline(0, color=".3", lw=1.2); ax.set_yticks(range(len(q)), labels, fontsize=10); ax.invert_yaxis()
        ax.set_xlabel("Paired difference in final accuracy (pp)")
        ax.legend(handles=[Line2D([0],[0], color="#333333", marker="o", label="budget-matched contrast"),
                           Line2D([0],[0], color="#8C564B", marker="o", label="permuted allocation (not matched)")], frameon=False, loc="lower right", fontsize=10)
        a = str(alpha).replace(".", "_")
        save(fig, "04_ablation", f"paired_contrasts_alpha{a}",
             f"Paired 95% confidence intervals for the controlled ablation on CIFAR-10 at $\\alpha={alpha:g}$ (30 seeds). Positive values favour the first arm named in each contrast. The permuted allocation is shown separately because its update budget is not matched.",
             f"fig:ablation-{a}")


def plot_drift() -> None:
    d = pd.read_csv(DRIFT); d = d[d.n_samples > 0]
    for alpha in [1., .1, .01]:
        fig, ax = plt.subplots(figsize=(6.5, 4.6)); present = []
        for method in ORDER:
            q = d[np.isclose(d.alpha, alpha) & (d.metodo == method)]
            if q.empty: continue
            ax.scatter(q.H_k, q.cos_sim, s=12, alpha=.38, color=COLORS[method], label=name(method), edgecolors="none")
            present.append(method)
        ax.set_xlabel(r"Heterogeneity score $H_k$"); ax.set_ylabel("Cosine similarity to aggregated update")
        ax.legend(frameon=False, loc="lower left", ncol=2)
        a = str(alpha).replace(".", "_")
        save(fig, "05_drift_proxy", f"Hk_vs_cosine_alpha{a}",
             f"Observed client-update alignment versus $H_k$ on CIFAR-10 at $\\alpha={alpha:g}$. Each point is a client-round observation; clients with no samples are excluded.",
             f"fig:drift-alignment-{a}")
    fh = d[d.metodo == "FedHAD"]
    fig, ax = plt.subplots(figsize=(6.5, 4.6))
    ax.scatter(fh.H_k, fh.E_k, color=COLORS["FedHAD"], alpha=.45, s=14, label=r"$E_k$")
    ax.set_xlabel(r"Heterogeneity score $H_k$"); ax.set_ylabel(r"Local epochs $E_k$", color=COLORS["FedHAD"]); ax.tick_params(axis="y", labelcolor=COLORS["FedHAD"])
    twin = ax.twinx(); twin.scatter(fh.H_k, fh.lr_k, color="#333333", marker="x", alpha=.5, s=16, label=r"$\eta_k$")
    twin.set_ylabel(r"Learning rate $\eta_k$", color="#333333"); twin.tick_params(axis="y", labelcolor="#333333"); twin.grid(False)
    ax.legend(handles=[Line2D([0],[0], color=COLORS["FedHAD"], marker="o", lw=0, label=r"$E_k$"), Line2D([0],[0], color="#333333", marker="x", lw=0, label=r"$\eta_k$")], frameon=False, loc="best")
    save(fig, "05_drift_proxy", "fedhad_control_rule", "FedHAD local epochs and learning rate assigned from the heterogeneity score in the drift-diagnostic runs. Static partitions make these client-level assignments constant across rounds.", "fig:drift-control")


def plot_prior() -> None:
    d = pd.read_csv(PRIOR)
    fig, ax = plt.subplots(figsize=(6.5, 4.6))
    changed = d.epochs_differ.astype(bool)
    ax.scatter(d.loc[~changed, "cv_norm"], d.loc[~changed, "js_global"], color="#7F7F7F", alpha=.35, s=13, label="same epoch allocation", edgecolors="none")
    ax.scatter(d.loc[changed, "cv_norm"], d.loc[changed, "js_global"], color=COLORS["FedHAD"], alpha=.45, s=13, label="different epoch allocation", edgecolors="none")
    ax.set_xlabel("Normalised CV (uniform reference)"); ax.set_ylabel("JS divergence to empirical global prior")
    ax.legend(frameon=False, loc="best")
    save(fig, "06_prior_assumption", "femnist_cv_vs_global_prior", "FEMNIST writers under the current normalised-CV score and Jensen--Shannon divergence to the empirical global prior. Red points change the assigned epoch under budget-preserving quantile matching.", "fig:femnist-prior")


def write_readme() -> None:
    text = """# Individual figures for the revision

Auxiliary figures prepared during the revision; **none of them appears in the current
manuscript**, whose figures are mapped in `analysis/README.md`. Every artefact is generated by
`analysis/revision_consolidated_tables_figures/generate_individual_figures.py` from existing
results only, with the palette, marker mapping, typography and 300-dpi PDF/PNG export of
`analysis/main_campaign/figuras_artigo.py`. Each PDF has a same-named `.tex` figure float.

| Folder | Question covered | Figures |
|---|---|---|
| `01_efficiency` | accuracy against compute at the configured operating points (one point per method, not a frontier) and computation-to-target | four per-dataset plots and CIFAR-10 cost-to-target |
| `02_heterogeneity` | robustness under increasing skew, including FedNova | one plot per dataset |
| `03_long_horizon` | whether the severe-skew result survives a longer run | CIFAR-10 separately at alpha 0.5 and 0.01 |
| `04_ablation` | matched-budget and component controls | one forest plot per alpha |
| `05_drift_proxy` | relation of Hk to the raw update-alignment measure (which inherits the client-size effect of Section 6.4) and implemented control | one alignment plot per alpha plus control policy |
| `06_prior_assumption` | the uniform-global-prior limitation on FEMNIST | CV versus empirical-prior JS plot |

These figures predate part of the final evidence and do not include it: SCAFFOLD (Section 6.9),
the control batteries of Section 6.11 and the FEMNIST 50-round block. The `04_ablation` forest
plots show raw contrasts; the manuscript reports them with Holm adjustment (Table 15). Gaps that
remain in the manuscript: no long horizon at α = 0.1, no FedDyn, tuning for FedProx only, and no
instrumented runtime or energy measurement. The tables in `../tables/` retain the numeric detail
for FedNova coverage, partition verification and prior metrics.
"""
    (OUT / "README.md").write_text(text, encoding="utf-8")
    tex = "\n".join(f"\\input{{revision_consolidated_tables_figures/individual_figures/{p.parent.name}/{p.stem}}}"
                    for p in sorted(OUT.glob("*/*.tex"))) + "\n"
    (OUT / "all_figures.tex").write_text("% Select individual floats as needed; this file inputs all of them.\n" + tex, encoding="utf-8")


def main() -> None:
    master = pd.read_csv(MASTER)
    plot_pareto(master); plot_target(master); plot_heterogeneity(master); plot_long_horizon(master)
    plot_ablation(); plot_drift(); plot_prior(); write_readme()
    print(f"Created {len(list(OUT.glob('*/*.pdf')))} PDF figures in {OUT}")


if __name__ == "__main__":
    main()
